version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV
            python3 -m venv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python tests.py
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $IMAGE_NAME:$TAG .
            docker images
#            . venv/bin/activate
#            pyinstaller -F simpleapi.py
#            docker build -t Kalter-M/$IMAGE_NAME:$TAG .
#            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
#            docker push Kalter-M/$IMAGE_NAME:$TAG
#      - run:
#          name: Deploy app to Digital Ocean Server via Docker
#          command: |
#            ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"