version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker-compose up build
#      - restore_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
#      - run:
#          command: |
#            python3 -m venv venv
#            . venv/bin/activate
#            pip install -r requirements.txt
#      - save_cache:
#          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
#          paths:
#            - "venv"
#      - run:
#          name: Running tests
#          command: |
#            . venv/bin/activate
#            python3 tests.py
#      - store_artifacts:
#          path: test-reports/
#          destination: python_app
#      - run: # test what branch we're on.
#          name: "What branch am I on?"
#          command: echo ${CIRCLE_BRANCH}
#      - run: # test what branch we're on.
#          name: "Test var"
#          command: echo ${DOCKER_NAME}

#  build:
#    docker:
#      - image: circleci/python:3.6
#    steps:
#      - checkout
#      - setup_remote_docker
#      - run:
#          name: Load env
#          command: |
#            python3 -m venv venv
#            . venv/bin/activate
#            pip install -r requirements.txt
#      - run:
#          name: Build image
#          command: |
#            docker build -t $FULL_IMAGE_NAME .
#      - run: # test what branch we're on.
#          name: "show docker images"
#          command: docker images
#      - run: # test what branch we're on.
#          name: "build num"
#          command: echo ${BUILD_NUMBER}


workflows:
  build-deploy:
    jobs:
      - test
#      - build:
#          requires:
#            - test
#      - deploy:
#          requires:
#            - build
#          filters:
#            branches:
#              only: master